## Rails Group Capstone: Recipe app(final app)
AlphaNtihinduka/food_reciepe pull request #36
Opened 2022-11-20 02:31 UTC by aron-helu

## Rails Group Capstone: Recipe app(final app) :card_file_box: :memo: :+1: 

These are the proposed changes :recycle:  for this project :arrow_down: :

### Logic :1234: :bulb: 

- Login page and registration page:
   - Should be built with Devise.
- Food list
   -  Should display a list of food added by the logged-in user as in the wireframe (for teams with only 2 people - display also quantity of a given food).
   -  Should lead to a form that allows users to add new food.
- Recipes list:
  - Should display a list of recipes created by the logged-in user as in the wireframe.
   -  Should lead to recipe details.
   - If the user is the owner of the recipe, should allow the user to delete it.
- Public recipe list:
  - Should display a list of all public recipes ordered by newest as in the wireframe.
   - Should lead to recipe details.
- Recipe details:
  -If the recipe is public or the user is the owner of the recipe, should display the recipe details as in the wireframe.
  - If the user is the owner of the recipe, should lead to the form that allows the user to add new food.
- General shopping list view (only for a group that has less than 3 members):
  - Should show the list of food that is missing for all recipes of the logged-in user (compare the list of food for all recipes with the general food list of that user).
  - Should count the total food items and total price of the missing food.
  - Make sure there are no N+1 queries happening.
 - Create a navigation menu that allows users to open all of the pages you created.        

- Inventories list:
  - Should display a list of inventories created by the logged-in user as in the wireframe.
  - Should lead to inventory details.
  - If the user is the owner of the inventory, should allow to delete it.
- Inventory details:
  - Should display the inventory details as in the wireframe.
  - Should lead to a form that allows users to add new food.
- Recipe details:
  - Should have a modal to choose an inventory to create a shopping list with, as in the wireframe.
- Inventory shopping list:
  - Should show the list of food that is missing by comparing the food in the recipe with the food in the inventory.
  - Should count the total food items and total price of the missing food.

- Technical setup
  - Set up the repository on GitHub and use Gitflow.
  - Set up Devise for authentication.
 - Set up RSpec and Capybara testing libraries.

2022-11-20 04:05 UTC, codepantha requested changes
# STATUS: REQUIRES CHANGES ♻️ 

## Hi team 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ Used GitFlow
✔️ Good commit history
✔️ No linter errors

## Required Changes ♻️
_Check the comments under the review._

- [ ] Well done for writing tests for your project, however, you have a bunch of failing tests. They are too many to pinpoint individually so I attached an image below 👇 Please try to make them pass 👏 
![image](https://user-images.githubusercontent.com/46839548/202884816-fe39af34-691f-4dab-8cbe-981b292af430.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-20 04:05 UTC, codepantha commented on app/views/recipes/_recipe.html.erb
> +    </div>
- [x] Please let's make sure that the recipe card looks like the wireframe design guideline. I attached an annotated diagram that shows some elements which you need to remove from your recipe card so that it looks more closely like the wireframe.
- [x] Please remove the Prep time and Cooking time as it is not in the wireframe
- [x] Kindly add a remove button to enable authorized users to delete a given recipe 👍 
![image](https://user-images.githubusercontent.com/46839548/202881153-aee97d5a-1451-4e33-9a43-c0775b1eb174.png)

2022-11-20 04:05 UTC, codepantha commented on app/views/public_recipes/index.html.erb
> +          <span>&nbsp;<%= @prices.sum %></span>
- [ ] Please let's try to follow the layout of the wireframe for the public recipes index page. Kindly find attached the wireframe guidelines for this page below 👇 
### Wireframe Design
![image](https://user-images.githubusercontent.com/46839548/202881373-69465dde-1aca-4d5b-93fd-8afb0d22e7d0.png)
### Your Implementation
![image](https://user-images.githubusercontent.com/46839548/202881398-758aefab-2428-4103-9887-05056d50c4de.png)

2022-11-20 04:05 UTC, codepantha commented on app/views/recipes/show.html.erb
> +    <button class="generate-shopping-list-btn"> Generate Shopping list </button>
- [ ] The recipe show page should have a modal to choose an inventory to create a shopping list with, as in the wireframe. Unfortunately, this button does nothing when clicked at the moment. Please try to implement it 👍 
### Wireframe
![image](https://user-images.githubusercontent.com/46839548/202882501-f1166a34-0e3f-4254-9a5f-c3b0ec81fbf4.png)
### Your Implementation
![image](https://user-images.githubusercontent.com/46839548/202883223-ec521549-baf4-46ca-a3eb-086085242ef1.png)

2022-11-20 04:05 UTC, codepantha commented on app/views/inventories/index.html.erb
> +</div>
- [x] Please let us try to follow the design guidelines as strictly as possible. In this case, please ensure to follow the same layout for the inventory cards as shown below 👇 
- [ ] Please add a Remove button so that authorized users may be able to delete a given inventory 👍 
### Wireframe Design
![image](https://user-images.githubusercontent.com/46839548/202883335-1973b87d-eb76-4e2e-943a-7a989c96081b.png)

### Your Implementation
![image](https://user-images.githubusercontent.com/46839548/202883300-05eb59be-2896-4711-8180-7132e48ec916.png)

2022-11-20 04:05 UTC, codepantha commented on app/views/inventories/show.html.erb
> +<button class="add_inventory_food_btn">Add inventory food</button>
- [ ] Users should be able to add new food to the inventory but when I click the "Add inventory food" button, nothing happens. Please try to implement this 🙏 
![image](https://user-images.githubusercontent.com/46839548/202884619-cf7ead91-8557-4c48-8b7e-fa99b5143255.png)

2022-11-21 12:10 UTC, medaminedev66 requested changes
Hi team 😃,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linters errors.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-21 12:10 UTC, medaminedev66 commented on app/views/recipes/show.html.erb
> +    <button class="generate-shopping-list-btn"> Generate Shopping list </button>
- [x] As requested by the previous reviewer, the user should be able to generate the shopping list by clicking on the "Generate shopping list" button. The button is still not clickable. Kindly work on that.

2022-11-21 12:10 UTC, medaminedev66 commented on app/views/inventories/index.html.erb
> +</div>
- [x] Great job working on the design of the inventory cards, but I still cannot see the remove button in the inventory card. As requested by the previous reviewer the user should be able to remove an inventory item, if the user is the owner of the inventory. Kindly work on that.

2022-11-21 12:10 UTC, medaminedev66 commented on app/views/inventories/show.html.erb
> +<button class="add_inventory_food_btn">Add inventory food</button>
- [x] The "Add inventory food" button is still not clickable. As requested by the previous reviewer, the users should be able to add new food to the inventory. Kindly work on that.

2022-11-21 12:10 UTC, medaminedev66 commented on app/views/public_recipes/index.html.erb
> +          <span>&nbsp;<%= @prices.sum %></span>
- [x] Great job working on the layout design of the public recipes page. But the layouts still do not match the provided wireframes. The public recipes should be below each other. Kindly work on that:

<img width="900" alt="image" src="https://user-images.githubusercontent.com/77190203/203045858-c1590f21-ce94-4c3e-adbd-e6bb2dc64453.png">

2022-11-21 12:10 UTC, medaminedev66 commented on app/views/recipes/_recipe.html.erb
> +    </div>
- [ ] The recipe card looks like the wireframe design guideline. Great work 👍 . But the "remove" button does not work as expected. When I click on the remove button, it takes me to the recipe show page. Kindly fix that and ensure the users is able to remove a recipe item only if they're the owner.

2022-11-21 12:10 UTC, medaminedev66 commented on app/views/foods/_food.html.erb
> +  </tr>
[OPTIONAL]
- The delete button in the food card does not function as expected. It shows the following error when I try to remove food due to the dependencies between recipe_foods and foods tables:
<img width="856" alt="image" src="https://user-images.githubusercontent.com/77190203/203049484-c5544405-6172-4977-a241-1905bf5752ae.png">
I highly recommend fixing this issue for a better user experience.

2022-11-21 15:30 UTC, AlphaNtihinduka commented
Dear @medaminedev66 
We have applied the required changes. You may consider us for review. 
Thank you.

2022-11-21 19:14 UTC, medaminedev66 requested changes
Hi team 😃,


You've done well implementing some of the requested changes 👏, but there are still some which aren't addressed yet.


 ## Highlights
- The user can generate the shopping list. Great job 👏 .

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-21 19:14 UTC, medaminedev66 commented on app/views/recipes/_recipe.html.erb
> +</div>
- [ ] In the "Recipies list" page,  The delete button is still dysfunctional. When I click on the "delete" button, the page reloads without any action. Kindly ensure that the owner can remove the recipes from the Recipes list page.
- [ ] In the "Recipe details" page, clicking on the recipe button shows the error below. When a recipe contains food, the user cannot delete it. To solve that, I recommend reading [this conversation](https://stackoverflow.com/questions/48739646/pgforeignkeyviolation-error-update-or-delete-on-table-xxx-violates-foreign) in StackOverflow.

<img width="909" alt="image" src="https://user-images.githubusercontent.com/77190203/203138870-ee6bbdaa-4438-4e10-b850-27b2de6bef08.png">

2022-11-21 19:54 UTC, AlphaNtihinduka commented
Dear @medaminedev66 
We greatly appreciate your precious time towards reviewing our project. We have applied the required changes. Thank you.

2022-11-21 21:00 UTC, bimbolabuari reviewed
Hi  Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- User can delete recipe lists and details 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-21 21:03 UTC, merged